### ISSUE TITLE
cannot read hasRoles of `undefined`

### ISSUE THREAD

**Issue by TobiTenno** [kristenmills/hubot-command-blacklist#5]
I get the following errors when attempting to use without hubot-auth installed.

```
ERROR TypeError: Cannot read property 'hasRole' of undefined
   at TextListener.callback (hubot/node_modules/hubot-command-blacklist/src/blacklist.js:68:17)
   at hubot/node_modules/hubot/src/listener.coffee:65:12
   at allDone (hubot/node_modules/hubot/src/middleware.coffee:44:37)
   at hubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
   at hubot/node_modules/hubot/node_modules/async/lib/async.js:154:25
   at hubot/node_modules/hubot/node_modules/async/lib/async.js:271:17
   at nextFunc (hubot/node_modules/hubot/src/middleware.coffee:33:35)
   at hubot/node_modules/hubot-command-blacklist/src/command-middleware.js:16:11
   at hubot/node_modules/hubot/src/middleware.coffee:36:24
   at hubot/node_modules/hubot/node_modules/async/lib/async.js:269:13
   at iterate (hubot/node_modules/hubot/node_modules/async/lib/async.js:146:13)
   at Object.async.eachSeries (hubot/node_modules/hubot/node_modules/async/lib/async.js:162:9)
   at Object.async.reduce (hubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
   at hubot/node_modules/hubot/src/middleware.coffee:49:13
   at _combinedTickCallback (internal/process/next_tick.js:67:7)
   at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by kristenmills** [comment]
I haven't looked at this in awhile so it's probably not up to date. I'll get a new release out that addresses this  and #6

**Comment by TobiTenno** [comment]
Any thoughts on it so far?

**Comment by kristenmills** [comment]
Haven't had a chance to look. I always welcome pull requests if you want to take a stab at it.

**Comment by TobiTenno** [comment]
I've got a fix for it, but i made a new module for it, because it relies on adapter-specific code.

I'll pull the fixes for it into a direct fork for it here.
